// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migraciones / introspección requieren conexión DIRECTA (5432).
    // El pooler de Supabase (6543, pgbouncer) no soporta el protocolo de
    // migraciones ni los locks que Prisma necesita.
    // El runtime (app/lib/prisma.ts) sigue usando DATABASE_URL pooled.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
