/**
 * Set semántico de iconos. Toda la UI importa desde acá, no de `lucide-react`
 * directamente — así un cambio de set/lib (o un alias renombrado) ocurre en un solo
 * lugar.
 */
export {
  AlertTriangle as AlertIcon,
  ArrowLeft,
  ArrowRight,
  ArrowUpDown as Sort,
  ArrowUpRight,
  Bell,
  Briefcase,
  Building2 as Building,
  Calendar,
  Check,
  CheckCircle,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsLeft,
  ChevronsRight,
  CircleAlert as AlertCircle,
  CircleHelp as Help,
  Clock,
  Coins,
  Download,
  Eye,
  EyeOff,
  FileText,
  Filter,
  Forward,
  Image as ImageIcon,
  Inbox,
  LayoutDashboard as Dashboard,
  Lock,
  LogOut as Logout,
  Mail,
  Menu,
  MessageCircle as WhatsApp,
  Moon,
  Newspaper,
  MoreHorizontal as More,
  Paperclip,
  Pencil as Edit,
  Phone,
  Plus,
  RefreshCw as Refresh,
  Reply,
  Search,
  Send,
  Settings,
  Shield,
  ShieldCheck,
  Sparkles,
  Sun,
  Tag,
  Trash2 as Trash,
  TrendingDown as TrendDown,
  TrendingUp as TrendUp,
  User,
  UserPlus,
  Users,
  Wallet,
  X as Close,
  XCircle,
} from "lucide-react";
